# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-30 13:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacthirecycle', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactus',
            name='email_address',
            field=models.EmailField(default='nakitamccool@gmail.com', max_length=254),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
