# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-30 13:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacthirecycle', '0002_auto_20170330_1350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='email_address',
            field=models.EmailField(max_length=254),
        ),
    ]
