# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-04 13:05
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Advert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=200)),
                ('item', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('condition', models.CharField(max_length=200)),
                ('available_from', models.DateTimeField(blank=True, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('views', models.IntegerField(default=0)),
                ('image', models.ImageField(blank=True, null=True, upload_to=b'images')),
                ('pickup_location', models.CharField(max_length=200)),
                ('original_retail_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('daily_rental_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('advertiser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
