# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-29 13:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adverts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advert',
            name='pickup_location',
            field=models.CharField(max_length=200),
        ),
    ]
