# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-04 21:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adverts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advert',
            name='available_from',
        ),
    ]
