# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-29 14:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adverts', '0002_auto_20170329_1358'),
    ]

    operations = [
        migrations.AddField(
            model_name='advert',
            name='original_retail_price',
            field=models.IntegerField(default=0),
        ),
    ]
