# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-29 14:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adverts', '0003_advert_original_retail_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='advert',
            name='insurance_package',
            field=models.CharField(default=b'None', max_length=100),
        ),
    ]
