# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-29 15:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adverts', '0010_auto_20170329_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advert',
            name='daily_insurance_cover_rate',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='advert',
            name='daily_rental_rate',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='advert',
            name='insurance_package',
            field=models.DecimalField(choices=[(1.0, b"I don't need insurance"), (1.2, b'Bronze'), (1.4, b'Silver'), (1.5, b'Gold')], decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='advert',
            name='original_retail_price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
