# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-29 16:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adverts', '0013_auto_20170329_1601'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advert',
            name='no_longer_needed',
        ),
    ]
