# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-29 17:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adverts', '0015_auto_20170329_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insurancepackage',
            name='insurance_package',
            field=models.CharField(choices=[(1.0, b"I don't need insurance"), (1.2, b'Bronze'), (1.4, b'Silver'), (1.5, b'Gold')], default=1.0, max_length=10),
        ),
    ]
