# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-29 17:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adverts', '0016_auto_20170329_1710'),
    ]

    operations = [
        migrations.AddField(
            model_name='insurancepackage',
            name='insurance_package_rate',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=4),
        ),
        migrations.AlterField(
            model_name='insurancepackage',
            name='insurance_package',
            field=models.CharField(choices=[(b"I don't need insurance", b"I don't need insurance"), (b'Bronze', b'Bronze'), (b'Silver', b'Silver'), (b'Gold', b'Gold')], default=b"I don't need insurance", max_length=10),
        ),
    ]
