# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-29 17:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adverts', '0018_auto_20170329_1716'),
    ]

    operations = [
        migrations.AddField(
            model_name='advert',
            name='insurance_package',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='adverts.InsurancePackage'),
            preserve_default=False,
        ),
    ]
