# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-31 15:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adverts', '0019_advert_insurance_package'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insurancepackage',
            name='insurance_package',
            field=models.CharField(choices=[(b"I don't need insurance", b"I don't need insurance"), (b'Bronze', b'Bronze'), (b'Silver', b'Silver'), (b'Gold', b'Gold')], max_length=100),
        ),
        migrations.AlterField(
            model_name='insurancepackage',
            name='insurance_package_rate',
            field=models.DecimalField(decimal_places=2, default=1.1, max_digits=4),
        ),
    ]
