# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-31 15:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adverts', '0020_auto_20170331_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insurancepackage',
            name='insurance_package_rate',
            field=models.DecimalField(decimal_places=2, default=1.11, max_digits=4),
        ),
    ]
